version: 2
jobs:
  build:
    working_directory: ~/learning_cicd
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          PG_HOST: 127.0.0.1
          PG_USER: m1k
          RAILS_ENV: production
          RACK_ENV: production
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: circleci/postgres:9.6-jessie
        environment:
          POSTGRES_USER: m1k
          POSTGRES_DB: m1k
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://m1k@127.0.0.1:5432/m1k"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter