version: 2
jobs:
  build:
    working_directory: ~/learning_cicd
    
    # Primary container image where all commands run
    
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          RAILS_ENV: production
          PGHOST: 127.0.0.1
          PGUSER: root
          PGPASSWORD: ""
    
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: m1k_pd
          POSTGRES_PASSWORD: ""
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Installing Dependencies
          command: |
            yarn install
            sudo apt-get install postgresql-client

       
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Running Test
          command: |
            psql -h localhost -p 5432 -c "select table_name from information_schema.tables where table_schema = 'public'" m1k_pd
      
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:schema:load --trace
            bundle exec rake db:migrate

      - run:
          name: Running Test
          command: |
            psql -h localhost -p 5432 -c "select table_name from information_schema.tables where table_schema = 'public'" m1k_pd
            psql -h localhost -p 5432 -c "select * from posts" m1k_pd

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter