version: 2
jobs:
  build:
    working_directory: ~/learning_cicd
    
    # Primary container image where all commands run
    
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          RAILS_ENV: production
          PGHOST: 127.0.0.1
          PGUSER: root
          PGPASSWORD: ""
          SECRET_KEY_BASE: 839ad58b0eac562b502c53184697579da577cd6d07e4775e9aeb1a9a10dc926dbcd14b1c89757d7d65cb40b35b6d7564330d07503f25812364dbd7ef13e002b7
    
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: m1kdb
          POSTGRES_PASSWORD: ""
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: rails-m1k-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # - run:
      #     name: Installing Dependencies
      #     command: |
      #       yarn install
      #       sudo apt-get install postgresql-client

      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Waiting for PostgreSQL to start
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 2
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Running Test
          command: |
            psql -h localhost -p 5432 -c "select table_name from information_schema.tables where table_schema = 'public'" m1kdb
      
      - run: 
          name: Setup DB
          command: |
            RAILS_ENV=production bundle exec rake db:create db:schema:load --trace
            RAILS_ENV=production bundle exec rake db:migrate
            RAILS_ENV=production bundle exec rake db:seed
      # - run:
      #     name: Rollback migration 
      #     command: |
      #.      bundle exec rake db:environment:set db:drop db:create db:migrate db:seed
      #       bundle exec rake db:rollback
      
      # - run: 
      #     name: Exec migration
      #     command: |
      #       bundle exec rake db:migrate
      #       bundle exec rake db:seed

      - run:
          name: Running Test
          command: |
            psql -h localhost -p 5432 -c "select table_name from information_schema.tables where table_schema = 'public'" m1kdb
            psql -h localhost -p 5432 -c "select * from greetings" m1kdb

      # - run:
      #     name: Parallel RSpec
      #     command: |
      #       RAILS_ENV=test bundle exec rake db:drop
      #       RAILS_ENV=test bundle exec rake db:create
      #       RAILS_ENV=test bundle exec rake db:migrate
      #       bundle exec rspec

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter