version: 2
jobs:
  build:
    working_directory: ~/learning_cicd
    docker:
      - image: ruby:2.7.0-node-browsers
        environment:
          PG_HOST: localhost
          PG_USER: m1k
          RAILS_ENV: test
          RACK_ENV: test
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: postgres:9.6-jessie
        environment:
          POSTGRES_USER: m1k
          POSTGRES_DB: m1k
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
     
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/m1k"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter