default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: m1k

production:
  <<: *default
  database: m1k_pd
  username: root
  password: ''


