default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: m1k

test:
  <<: *default
  database: m1k_test

production:
  <<: *default
  database: m1kdb
  username: root
  password: ''